### ISSUE TITLE
出错

### ISSUE THREAD

**Issue by hcym** [xyuanmu/XX-Mini#103]
上个python2版本和python3都正常

今天的出错，信息是：

Traceback (most recent call last):
  File "proxy.py", line 71, in <module>
    import proxy_handler
  File "/dev/shm/XX-Mini/lib/proxy_handler.py", line 14, in <module>
    from cert_util import CertUtil
  File "/dev/shm/XX-Mini/lib/cert_util.py", line 298
SyntaxError: Non-ASCII character '\xe5' in file /dev/shm/XX-Mini/lib/cert_util.py on line 298, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

麻烦xyuanmu看看

**Comment by xyuanmu** [comment]
抱歉，居然有中文。

**Comment by xyuanmu** [comment]
:joy: 已经更新了，重新下载即可。

**Comment by hcym** [comment]
抱歉，还是不对劲

Traceback (most recent call last):
  File "proxy.py", line 71, in <module>
    import proxy_handler
  File "/dev/shm/XX-Mini/lib/proxy_handler.py", line 16, in <module>
    import gae_handler
  File "/dev/shm/XX-Mini/lib/gae_handler.py", line 20, in <module>
    from appids_manager import appid_manager
  File "/dev/shm/XX-Mini/lib/appids_manager.py", line 8, in <module>
    import check_ip
  File "/dev/shm/XX-Mini/lib/check_ip.py", line 12, in <module>
    import socks
  File "/dev/shm/XX-Mini/lib/socks.py", line 9, in <module>
    from ip_utils import check_ip_valid
  File "/dev/shm/XX-Mini/lib/ip_utils.py", line 19
SyntaxError: Non-ASCII character '\xe6' in file /dev/shm/XX-Mini/lib/ip_utils.py on line 19, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by xyuanmu** [comment]
再次更新文件了，看来得找个英文系统测试才行。

**Comment by hcym** [comment]
谢谢

OK了，还有个小情况

python2版不能终端终止退出

python3版正常
😂

**Comment by xyuanmu** [comment]
不能终端退出？是 Ctrl+C 不能退出吗？
打开 proxy.py 修改201行 sys.exit() 为 os._exit() 试试

**Comment by jzp820927** [comment]
终于出心版本了，不容易啊

**Comment by xyuanmu** [comment]
@jzp820927 之前电脑坏了，现在换台新的发现在移动网络下gae速度比蓝灯还变态，那专业版被坑的感觉。

**Comment by jzp820927** [comment]
只要 xy 大能回归，我们就满足啦。

**Comment by xyuanmu** [comment]
是啊，不过总有不好的预感，移动会步电信后尘，到时候又苦逼了

**Comment by hcym** [comment]
谢 x 大

都好了

**Comment by jzp820927** [comment]
这个东西大概估计也不是因为电信的线路差，而是用户基数大，大家都挤在哪点可怜的国际带宽上，自然快不起来。目前移动速度快，应该也是因为用户基数小，所以速度就快。如果大家都跑去用移动带宽了，电信的国际带宽用户量就会变小，电信就会比移动好了。主要还是看用户的变动。

**Comment by hcym** [comment]
电信还行吧

高峰时确实出口带宽缩水严重。国内没影响

hosts谷歌境内服务器下载妥妥的满速

非高峰时就BT了。代理下载境外资源经常超过签约带宽

中国企业能做到这样的也够意思咯

**Comment by jzp820927** [comment]
非高峰时都在上班，肯定速度快了
