### ISSUE TITLE
Ubuntu lunach error

### ISSUE THREAD

**Issue by bg1rgb** [xyuanmu/XX-Mini#109]
root@ubuntu:/home/trevor/Downloads/XX-Mini# python proxy.py
Traceback (most recent call last):
  File "proxy.py", line 26, in <module>
    from config import config
  File "/home/trevor/Downloads/XX-Mini/lib.egg/config.py", line 10, in <module>
ImportError: No module named OpenSSL

**Comment by wzdnzd** [comment]
装openssl

**Comment by jzp820927** [comment]
https://github.com/xyuanmu/XX-Mini/wiki/No-module-named-OpenSSL

**Comment by jeffliusky** [comment]
command:
`sudo pip install pyopenssl`
