### ISSUE TITLE
1.2.9 linux 有几处[Error]是什么问题

### ISSUE THREAD

**Issue by GerGitHub** [xyuanmu/XX-Mini#114]
在DSM中跑的
DiskStation> python /XX-Lin/proxy.py
--------------------------------------------------------------------------------
XX-Mini Version     : 1.2.9 (python/2.7.9 pyopenssl/0.13)
Listen Address      : 127.0.0.1:8087
Setting File        : proxy.ini
GAE APPID           : Using Public APPID
Pac Server          : http://127.0.0.1:8086/proxy.pac
CA File             : http://127.0.0.1:8086/CA.crt
Pac File            : file:///XX-Lin/data/proxy.pac
--------------------------------------------------------------------------------
Oct 20 17:58:50.138 - [INFO] SSL use version:TLSv1
Oct 20 17:58:50.139 - [INFO] OpenSSL dont't support npn/alpn, no HTTP/2 supporte                                   d.
Oct 20 17:58:50.145 - [INFO] load ip range file:/XX-Lin/ip_range.txt
Oct 20 17:58:50.213 - [INFO] OpenSSL dont't support npn/alpn, no HTTP/2 supporte                                   d.
Oct 20 17:58:50.226 - [INFO] no CA file exist
Oct 20 17:58:50.227 - [INFO] clean old site certs
Oct 20 17:58:50.227 - [INFO] generate CA file:/XX-Lin/data/CA.crt
Oct 20 17:58:50.636 - [INFO] create ca
Oct 20 17:58:50.637 - [ERROR] bind to 127.0.0.1:8087 fail:error(98, 'Address alr                                   eady in use')
Traceback (most recent call last):
  File "/XX-Lin/proxy.py", line 160, in <module>
    main()
  File "/XX-Lin/proxy.py", line 139, in main
    proxy_daemon = simple_http_server.HTTPServer((config.LISTEN_IP, config.LISTE                                   N_PORT), proxy_handler.GAEProxyHandler)
  File "/XX-Lin/lib.egg/simple_http_server.py", line 264, in __init__
  File "/XX-Lin/lib.egg/simple_http_server.py", line 269, in init_socket
  File "/XX-Lin/lib.egg/simple_http_server.py", line 279, in add_listen
Exception: bind to 127.0.0.1:8087 fail:error(98, 'Address already in use')

以提示完后开始扫描验证IP

Oct 20 18:00:50.337 - [INFO] good ip num:0, bad ip num:0
Oct 20 18:01:37.482 - [INFO] scan_ip add ip:176.255.201.142 time:440
Oct 20 18:01:50.401 - [INFO] good ip num:1, bad ip num:0
Oct 20 18:02:54.468 - [INFO] good ip num:0, bad ip num:1
Oct 20 18:03:21.805 - [INFO] scan_ip add ip:49.231.56.177 time:527
Oct 20 18:03:21.996 - [INFO] scan_ip add ip:157.197.93.41 time:2116
Oct 20 18:03:32.613 - [INFO] scan_ip add ip:87.79.22.246 time:1255
Oct 20 18:03:38.486 - [INFO] scan_ip add ip:41.201.164.171 time:620
Oct 20 18:03:44.255 - [INFO] scan_ip add ip:181.192.63.238 time:754
Oct 20 18:03:54.530 - [INFO] good ip num:5, bad ip num:1

**Comment by jzp820927** [comment]
Oct 20 17:58:50.637 - [ERROR] bind to 127.0.0.1:8087 fail:error(98, 'Address alr eady in use')

端口监听失败，8087 端口被占用，自己检查是什么进程占用了 8087 端口，把占用的进程结束掉，就可以了。
