### ISSUE TITLE
请教怎样在openwrt运行

### ISSUE THREAD

**Issue by jrkkei** [xyuanmu/XX-Mini#12]
小白一个，完全不懂linux，又找不到教程，自己瞎折腾结果当然是失败。。。求大神出手相助
# python /xx/proxy.py
--------------------------------------------------------------------------------
XX-Mini Version     : 1.1 (python/2.7.3 pyopenssl/0.10)
Listen Address      : 10.10.10.4:8087
GAE APPID           : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7..
Pac Server          : http://127.0.0.1:8086/proxy.pac
Pac File            : file:///xx/data/proxy.pac
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/xx/proxy.py", line 94, in <module>
    import proxy_handler
  File "/xx/lib.egg/lib/proxy_handler.py", line 7, in <module>
  File "/usr/lib/python2.7/ssl.py", line 60, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl

执行命令失败 (代码： 256)

**Comment by xyuanmu** [comment]
你的python库好像不全，看这：http://stackoverflow.com/questions/5128845/importerror-no-module-named-ssl
你需要重新编译python

**Comment by jrkkei** [comment]
谢谢回复，但我是真正意义上的小白，完全不能理解回帖的内容，我只会用GUI，python是从路由器里搜索安装的。。。请问能不能给出具体操作步骤

**Comment by jzp820927** [comment]
小白整这个，难度很大啊

**Comment by xyuanmu** [comment]
到 python 目录修改 /Modules/Setup.dist 改成如下，实际上就是去掉 _socket 和底下三行前面的注释符 #
```py
# Socket module helper for socket(2)
_socket socketmodule.c timemodule.c

# Socket module helper for SSL support; you must comment out the other
# socket line above, and possibly edit the SSL variable:
#SSL=/usr/local/ssl
_ssl _ssl.c \
-DUSE_SSL -I$(SSL)/include -I$(SSL)/include/openssl \
-L$(SSL)/lib -lssl -lcrypto
```
之后执行
```shell
make
make install #可能需要sudo或者root权限

**Comment by jrkkei** [comment]
@xyuanmu 非常抱歉，还是不懂，看来确实如 @jzp820927 所说，我还是放弃吧。因为win10卡声音我才想把xx搞到路由器上，原版太大装不下，mini给了我希望，然而自己无能。。。卡就卡吧，只好忍忍算了，耽误你时间了，对不起

**Comment by jzp820927** [comment]
等 xyuanmu 优化好了，你再考虑弄到 openwrt 上吧，现在这个项目才刚刚起步，bug 难免是有的，如果动手能力不强，很难弄。

**Comment by jrkkei** [comment]
@jzp820927 嗯，不过就算没了bug，以我这水平也。。。看来小白还是老老实实用原厂固件比较现实。。。

**Comment by xyuanmu** [comment]
对了，试试这个办法，你在 XX-Mini 目录新建一个 lib 文件夹，下载下面这张图片改后缀 jpg 为 zip 解压 _ssl.pyd 到那个 lib 目录看是否有效。

![1](https://cloud.githubusercontent.com/assets/12442896/13867836/f41ff97a-ecfd-11e5-8683-d09c871aab98.jpg)

**Comment by jrkkei** [comment]
@xyuanmu 是这样吗？好像不行啊
![default](https://cloud.githubusercontent.com/assets/17683750/13868411/5bba2998-ed03-11e5-980c-4f908595270f.JPG)

**Comment by xyuanmu** [comment]
@jrkkei 那再试试用压缩软件打开 lib.egg，或者将 lib.egg 改后缀为zip，将 _ssl.pyd 和 _socket.pyd 添加到压缩包的 lib 目录下，添加后再把后缀改回egg，如果还是不行估计这个模块不通用了。

**Comment by jrkkei** [comment]
@xyuanmu 还是不行，仍然是相同的错误信息
![default](https://cloud.githubusercontent.com/assets/17683750/13869813/a28e017c-ed13-11e5-99e2-390e75634b8e.JPG)

**Comment by xyuanmu** [comment]
@jrkkei 问一下，能不能不提取openwrt里的 python 文件夹出来，我测试下是否可以通过手动添加 Linux 的 ssl 模块来保证运行。

**Comment by jrkkei** [comment]
@xyuanmu 当然可以，但你得教我提取方法

**Comment by xyuanmu** [comment]
@jrkkei 我没用过openwrt，你找找看有木有 python 或者 python2.7 之类的文件夹。

**Comment by xyuanmu** [comment]
@jrkkei 对了，这是我在 OpenWrt 官网下载的ssl库，你试试解压到 XX-Mini 的 lib 目录是否有效。
[ssl.zip](http://xyuanmu.github.io/hack-iqiyi/ssl.zip)

**Comment by jrkkei** [comment]
@xyuanmu 图传不了，挂代理也不行。。。搜索结果只有2个9KB的文件，这应该不对吧，太小了
ssl.zip错误信息有变：
# python /xx/proxy.py
python: '/xx/lib/_ssl.so' is not an ELF executable for MIPS
python: '/xx/lib/_ssl.so' is not an ELF executable for MIPS
python: '/xx/lib/_ssl.so' is not an ELF executable for MIPS
--------------------------------------------------------------------------------
XX-Mini Version     : 1.1 (python/2.7.3 pyopenssl/0.10)
Listen Address      : 10.10.10.4:8087
GAE APPID           : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7..
Pac Server          : http://127.0.0.1:8086/proxy.pac
Pac File            : file:///xx/data/proxy.pac
--------------------------------------------------------------------------------
python: '/xx/lib/_ssl.so' is not an ELF executable for MIPS
Traceback (most recent call last):
  File "/xx/proxy.py", line 94, in <module>
    import proxy_handler
  File "/xx/lib.egg/lib/proxy_handler.py", line 7, in <module>
  File "/usr/lib/python2.7/ssl.py", line 60, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: File not found

执行命令失败 (代码： 256)

**Comment by jrkkei** [comment]
comment按钮也变灰不能按，这是怎么回事

**Comment by xyuanmu** [comment]
@jrkkei 你刚刚关了issue，所以变灰。看来 OpenWrt 和Windows不同，不是下载库就能直接使用，还要编译，如果解决不了ssl的问题，gae类的翻墙工具是用不了的。

**Comment by jzp820927** [comment]
xx不是有人成功在路由器  梅林固件 上运行过麽，可以参考下

**Comment by jrkkei** [comment]
@xyuanmu 不是的，那个绿按钮先变灰，不得已才按了白的
@jzp820927 相关帖子我也看了，还是一如既往看不懂

**Comment by jzp820927** [comment]
opkg install pyopenssl

@jrkkei 这个你安装了没？

**Comment by jrkkei** [comment]
@jzp820927 安装了

**Comment by jzp820927** [comment]
那确实不知道是什么问题了，不过俺道理说，XX能够正常运行在 openwrt 上面，mini 应该也没问题。

**Comment by xyuanmu** [comment]
libopenssl 这个有安装吗？

**Comment by jrkkei** [comment]
@xyuanmu 也装了，版本号 	1.0.2f-1
如果大神愿意折腾，我可以开放路由器远程控制权（不过要等到周末），意下如何？
@jzp820927

**Comment by jzp820927** [comment]
叫 xyuanmu 给你远程吧，他才在真正的大神

**Comment by xyuanmu** [comment]
我都没用过 OpenWrt，怎么远程怎么连接的都不清楚

**Comment by jrkkei** [comment]
那就真的束手无策了

**Comment by jzp820927** [comment]
建议你去 xx-net 的 issue 去问问，那边人多，用 operwrt 的应该也有。

**Comment by jrkkei** [comment]
@xyuanmu @jzp820927 goagent能用xx就也能用吗？我找得到集成goagent的固件

**Comment by jzp820927** [comment]
应该没问题，XX 是 goagent 的二次开发，MINI 是XX的二次开发，核心都是一样的

**Comment by jrkkei** [comment]
@jzp820927 好吧这算最后一根救命稻草了，等折腾完了我回来汇报

**Comment by jrkkei** [comment]
成功啦！刷了集成goagent的固件，xx-mini可以直接运行，成功翻墙。一脉相承就是好啊，不过没有日志，开始还以为失败了。。。十分感谢二位相助 @xyuanmu @jzp820927

**Comment by jzp820927** [comment]
估计这个固件已经集成好了 完整的 python 和 openssl 环境。

**Comment by jrkkei** [comment]
装好时空余900KB空间，运行几天后只剩下200多KB，进程自动终止了，能不能不生成log文件呢？ini里[system]
log_file = 0
但还是生成了，这是bug吗？ @xyuanmu

**Comment by jzp820927** [comment]
你说的应该是 IP扫描日志文件。

**Comment by xyuanmu** [comment]
@jrkkei 暂时解决方法，到data目录删掉所有 scan_ip 开头的文件，设置这个文件为只读。下个版本加一个扫描日志的开关。

**Comment by jrkkei** [comment]
好的，谢谢。

**Comment by jzp820927** [comment]
这个日志文件还真是路由杀手，路由空间本来就小，确实不适合生成日志

**Comment by jrkkei** [comment]
日志文件加起来都比所有可用空间都大了，应该是压缩了吧

**Comment by jzp820927** [comment]
纯文本文件，哪来的压缩，又不是 zip，gz

**Comment by jrkkei** [comment]
是这样的，安装xxmini之前路由器可用空间1.2MB，空间还剩下200KB时，有3个800KB的日志文件，没压缩应该放不下吧

**Comment by jzp820927** [comment]
那就不不知道了，只要不产生日志文件就行了

**Comment by jrkkei** [comment]
好像不行啊，设置了只读，但文件还是照样变大，是我设置方法不对吗？
![default](https://cloud.githubusercontent.com/assets/17683750/14098264/8f7bc942-f5ac-11e5-9228-bcd885e5c7c5.JPG)

**Comment by jzp820927** [comment]
权限看着没问题，但是不应该啊，只读权限是不可能可以写数据进去的

**Comment by xyuanmu** [comment]
看来那个只读没有起到什么作用，帮忙测试下这个版本能不能在 OpenWrt 里运行：[XX-Mini_linux.zip](https://github.com/xyuanmu/XX-Mini/releases/download/untagged-5b95b878bf2c9ece8d96/XX-Mini_linux.zip)，这个版本已经可以设置扫描IP的日志，修改 proxy.ini，log_scan = 0 即不会输出日志。

**Comment by jrkkei** [comment]
@xyuanmu 404

**Comment by xyuanmu** [comment]
抱歉，没想到要发布第三方才能下：https://github.com/xyuanmu/XX-Mini/releases/download/1.2.3/XX-Mini_linux.zip

**Comment by jrkkei** [comment]
@xyuanmu 跑了一会儿，一切正常，日志文件保持0KB不变，多谢

**Comment by jrkkei** [comment]
又遇到新问题，所有http网站，不论是否被墙，全都连不上，一直“正在连接”，https没问题。昨天晚上试过http是可以正常打开的，今天就不行了

**Comment by jrkkei** [comment]
返回1.1版本没问题，昨天可能是没重启路由器，缓存造成的错觉吧 @xyuanmu

**Comment by xyuanmu** [comment]
哪个版本开始http无法连接？

**Comment by xyuanmu** [comment]
哪个版本开始http无法连接？

**Comment by jrkkei** [comment]
我只用过1.1和最新（可关log那个），其他的没试，需要测试吗？

**Comment by xyuanmu** [comment]
不需要，你下载最新版：[XX-Mini_linux_darwin_v1.2.3.zip](https://github.com/xyuanmu/XX-Mini/releases/download/1.2.3/XX-Mini_linux_darwin_v1.2.3.zip) 打开 proxy.py，删掉下面两行代码试试：
```py
    import threading
    threading.stack_size(128*1024)

**Comment by jrkkei** [comment]
@xyuanmu 正常了

**Comment by xyuanmu** [comment]
哦，好的

**Comment by jrkkei** [comment]
@xyuanmu 万分抱歉，我tm又忘记了重启路由器，重启后还是不行，http连接不上

**Comment by xyuanmu** [comment]
那这样就麻烦了，能不能劳烦你 [1.2.1](https://github.com/xyuanmu/XX-Mini/releases/download/1.2/XX-Mini_linux_v1.2.1.zip)、[1.2.2](https://github.com/xyuanmu/XX-Mini/releases/download/1.2.2/XX-Mini_linux_v1.2.2.zip) 都测试下，看是那个版本开始的？

**Comment by jrkkei** [comment]
好的

**Comment by jrkkei** [comment]
@xyuanmu 很不幸，全军覆没，路由器没忘重启。

**Comment by xyuanmu** [comment]
那你先用着 [1.1.1](https://github.com/xyuanmu/XX-Mini/releases/download/1.1/XX-Mini_linux_v1.1.1.zip) 版本。去掉扫描日志输出的方法：
* 用压缩软件打开 lib.egg，或者将 lib.egg 改后缀为zip
* 解压 lib\google_ip.py 出来
* 删掉下面5行代码，第548-552行
* 将新的 google_ip.py 再替换回去，这样就不会输出日志了。
```py
                    import re
                    log = scan_ip_log.get_log_content()
                    log_ip = re.compile(r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}',re.S).findall(log)
                    if ip not in log_ip:
                        scan_ip_log.info("Add %s time:%d CN:%s ", ip, result.handshake_time, result.domain)

**Comment by jrkkei** [comment]
谢谢

**Comment by xyuanmu** [comment]
打扰一下，因为1.2版本开始无法连接http，判断有可能是认证功能导致了，有时间的话帮忙测试下：
* 下载 [r01.zip](https://raw.githubusercontent.com/xyuanmu/XX-Mini/testfile/r01.zip)
* 备份现在的 proxy.py 和 lib.egg，解压 r01 的文件替换
* 重启路由器，看是否解决http连接的问题
* 谢谢！

**Comment by jrkkei** [comment]
@xyuanmu 不用这么客气，帮忙测试也是应该的。
结果：替换后1.1也不能打开http了

**Comment by jrkkei** [comment]
另外发现google也不行了，不过有提示：连接超时，先休息一会再来！ http是完全没反应的。youtube能看，其他https能连。

**Comment by xyuanmu** [comment]
谷歌无法打开估计跟IP有关，今天挂了很多IP，你再试试 [r02.zip](https://raw.githubusercontent.com/xyuanmu/XX-Mini/testfile/r02.zip)

**Comment by jrkkei** [comment]
仍然不行

**Comment by xyuanmu** [comment]
1.2版本可能导致连接问题的两个地方都无效，看来只能用回1.1.1版本了，修改了一份没有生成日志的，去掉自带的OpenSSL可以减少占用的空间，你替换下吧：[r1.1.1-no-scan-log.zip](https://raw.githubusercontent.com/xyuanmu/XX-Mini/testfile/r1.1.1-no-scan-log.zip)

**Comment by jrkkei** [comment]
替换了，正常了，谢谢

**Comment by jzp820927** [comment]
IP都已经死绝了，别再折腾了，大家洗洗睡吧！

**Comment by xyuanmu** [comment]
@jrkkei 不好意思，又要麻烦你了！今天查看了commit记录，发现还有一个地方可能导致http无法连接，你抽空帮忙测试下，谢谢！ [r03.zip](https://raw.githubusercontent.com/xyuanmu/XX-Mini/testfile/r03.zip)

**Comment by jrkkei** [comment]
@xyuanmu 失败。我会帮忙测试直到修复，尽管来吧
@jzp820927 这种事也不是一两次了，没必要这么悲观吧

**Comment by xyuanmu** [comment]
好的，那我就不客气了，试试这个版本：https://raw.githubusercontent.com/xyuanmu/XX-Mini/testfile/r04.zip

**Comment by jrkkei** [comment]
r04失败。

**Comment by xyuanmu** [comment]
麻烦再试试：[r05.tar.gz](https://github.com/xyuanmu/XX-Mini/files/200725/r05.tar.gz)

**Comment by jrkkei** [comment]
r05失败。

**Comment by xyuanmu** [comment]
再试试这个版本：[r06.tar.gz](https://github.com/xyuanmu/XX-Mini/files/200729/r06.tar.gz)

**Comment by jrkkei** [comment]
@xyuanmu r06成功！

**Comment by jrkkei** [comment]
在firefox和chrome上都测试了http,https的网站，全能打开

**Comment by xyuanmu** [comment]
好的，基本定位问题，为了确认，麻烦再测试最后一个版本：[07.tar.gz](https://github.com/xyuanmu/XX-Mini/files/200733/07.tar.gz)

**Comment by jrkkei** [comment]
07换了今天从没访问过的网站测试，一切正常。

**Comment by xyuanmu** [comment]
好的，知道问题了，谢谢你的测试！

**Comment by jrkkei** [comment]
不客气

**Comment by xyuanmu** [comment]
试用下1.2.4版本，如果没事那下个版本就按照这个发布了：[1.2.4-beta.tar.gz](https://github.com/xyuanmu/XX-Mini/files/200741/1.2.4-beta.tar.gz)

**Comment by jrkkei** [comment]
稍等

**Comment by xyuanmu** [comment]
对了，这个版本可能会报错，用这份proxy.ini替换原来的：[ini.tar.gz](https://github.com/xyuanmu/XX-Mini/files/200752/ini.tar.gz)

**Comment by jrkkei** [comment]
没问题，顺便还试了自己的appid。开始忘了改监听ip，愣了半天才反应过来。。。
如果不用pac可以删除proxy.pac吗？

**Comment by xyuanmu** [comment]
可以删掉，不过删掉明天又会重新生成，修改proxy.ini：
```ini
[pac]
enable = 0

**Comment by jrkkei** [comment]
明白了，谢谢

**Comment by xyuanmu** [comment]
是我该谢谢你才对 :smile:

**Comment by jrkkei** [comment]
好吧，give and take^^

**Comment by jzp820927** [comment]
你们2个太牛B了，不是一般的有耐心。终于把路由器搞定了，看来 XX-Mini 又进步了一大步！可以开始转向手机端了

**Comment by jrkkei** [comment]
运行一星期，情况良好。虽然由于IP原因速度不如以前，但稳定性还是赞的，从youtube下载几个视频，共约10GB，顺利完成，在线观看也极少中断。从去年8月以来，终于用上了不卡声音的win10，还有点小激动呢。
出于好奇试了下p3 win版本（路由器上年纪了没有p3支持，可能以后也不会有了），感觉资源占用、翻墙体验没什么区别，倒是卡顿更厉害了，直接给卡黑屏了，大汗，好在并没死机，这还是第一次碰到，不知道是不是p3的问题，反正短时间内是不敢用了。。。

**Comment by jzp820927** [comment]
P3 在 linux 下性能要好些，win 就用 P2 吧

**Comment by shaoyan177** [comment]
佩服，谢谢楼上两位，我去倒腾下

**Comment by firefoxwang** [comment]
佩服楼上两位，我也准备把xx-net移动到openwrt上．

**Comment by firefoxwang** [comment]
今天运行的好好的出现了　Segmentation fault
的情况，  @jrkkei @xyuanmu 
是在openwrt里运行的，用的网件3800，淘宝买的洋垃圾．．．．
我把python，openssl，xx-mini-net　放在usb移动硬盘上运行
各位同学有见过吗

**Comment by xyuanmu** [comment]
试试在路由器里运行下面命令，看看会不会出现：
```py
python
import ctypes
```
感觉应该是python出问题了，有可能需要重装一遍。

**Comment by jrkkei** [comment]
@firefoxwang 我是帮不上忙的，因为我用的现成的固件，没有自己动手，抱歉

**Comment by firefoxwang** [comment]
@xyuanmu 可以import ctypes。。。。。。我之前有过直接在路由开机状况下拔出usb移动硬盘拷电影然后再直接插上去，用笔记本ssh到路由里继续跑proxy.py。。。顺便问一下在哪里可以设置开机启动，因为我ssh关了后,proxy也停了。。。

**Comment by firefoxwang** [comment]
@jrkkei 我看你之前的问题，应该跟python库有关系，最好用一个有usb接口的路由。淘宝3800才一百多块钱，可以刷成openwrt，然后加一个移动硬盘。把python和pyopenssl都装在移动硬盘里就应该可以import openssl了。这样搭建环境就没问题。

**Comment by jrkkei** [comment]
@firefoxwang 我的路由器有USB，但是我不愿意用，这是个人喜好问题。路由器除了基本的上网功能外，我只需要翻墙，所以在xx-mini已经成功运行的情况下，我并不想自己尝试搭建了，以我的能力估计也是浪费时间而已

**Comment by jzp820927** [comment]
@firefoxwang 开启启动可以写到启动脚本里面，比如 rc.local

**Comment by firefoxwang** [comment]
@jzp820927 openwrt中直接nohup不可以，不过（python xx-net.py $）后就直接显示后台运行了。thank you 我先就这么用着，有需要再更改。启动脚本我设置后.py程序没起得来，具体问题不太明白，等有空再去折腾

**Comment by jrkkei** [comment]
![default](https://cloud.githubusercontent.com/assets/17683750/15012455/50de0164-122b-11e6-98bc-863763561a12.JPG)
装好xxmini后随便搜了个脚本就能用，当然了，那些参数我是看不懂的

**Comment by jzp820927** [comment]
LS 正解

**Comment by ysjlion** [comment]
@jrkkei 看了上面对话，真心牛掰啊，求WR720N集成goagent的固件
PS：楼主是4M的flash吗？硬件有改动吗？

**Comment by jrkkei** [comment]
@ysjlion 我的是4530R，淘宝买的卖家刷好的，16M，硬件有无改动不知道。

**Comment by roc1010kmt** [comment]
@jrkkei 樓主4530R路由器,運行xxnet卡嗎?cpu占用多少?

**Comment by jrkkei** [comment]
@roc1010kmt 全速下载CPU占满，毕竟古董了，速度1-2MB/s

**Comment by roc1010kmt** [comment]
@jrkkei 看youtube之類的視頻卡嗎?
設置線程多少啊?

**Comment by ysjlion** [comment]
@jrkkei @xyuanmu @jzp820927 
折腾了好几天终于安装成功了，但是不是知道是不是配置错了，总上不去，facebook，youtube都打不开，192.168.1.1:8086/proxy.pac页面能显示，大神帮忙看下是啥问题。我是[listen]和[pac]的ip设置0.0.0.0

![qq 20160910140943](https://cloud.githubusercontent.com/assets/15059695/18408478/749c92b2-7763-11e6-8052-ba73c6700dec.jpg)

**Comment by jzp820927** [comment]
看日志没啥问题，不知道你怎么设置的代理

**Comment by ysjlion** [comment]
@jzp820927 解决了，果然是游览器代理问题，问题是我设置都是0.0.0.0，为什么还要单独设置代理，不是所有流量都走xxnet吗？还有个问题，我现在路由用的PPPoE模式接光猫拨号，如果我换成DHCP模式，采用光猫-路由1-路由2（本机）模式，xxnet的要怎么设置，原先的用不了了，感觉好复杂。

**Comment by jzp820927** [comment]
浏览器肯定是要单独设置代理的，这个又不是 vpn，莫非你还想，什么都不用设置，直接就能翻墙/

**Comment by jzp820927** [comment]
感觉你的接法好复杂，你的意思是 猫后面还要再接2个路由器？有这个必要麽？

**Comment by ysjlion** [comment]
@jzp820927 不是，光猫--路由1--路由2，一个接一个，我路由2装了openwrt是迷你的，发射功率小基本穿墙就不用想了，路由1正常拨号做电视等的无线，然后接出一Lan口接路由2，路由2就是我自己房间里小范围用的，只要求路由2翻墙，问题是路由2如果是AP模式的话xxnet就上不了，设置不知道要怎么整，弄了半天还不行

**Comment by jzp820927** [comment]
和什么模式没关系，你是想把 XXmini 部署到路由2上？

**Comment by ysjlion** [comment]
@jzp820927 对，昨晚弄的时候不知道什么弄错了，wan口和lan口好像都设置成DHCP了，晕倒，路由现在进不去，telnet也进不去，猛戳菊花出来uboot，直接重新刷机了，╮(╯▽╰)╭，哭死。

**Comment by jzp820927** [comment]
好像一般只有 lan 口可以 DHCP，wan 口一般不提供 dhcp

**Comment by jrkkei** [comment]
@roc1010kmt 在线基本360p，480p有时也能凑合，线程默认

**Comment by jzp820927** [comment]
普通路由器性能还是不行，我觉得 树莓派 最合适。

**Comment by ysjlion** [comment]
@jzp820927 树莓派也可以实现路由功能？那牛逼伤了，果断换树莓派啊~~！

**Comment by jzp820927** [comment]
你 google 搜索 树莓派 路由，就知道了，教程一大片。

**Comment by jrkkei** [comment]
鱼与熊掌啊，下台路由器干脆无视功耗直接上x86 pc得了。。。

**Comment by jzp820927** [comment]
X86 的肯定最好，兼容性最强，目前好像也有一些 X86 的单片机，和树莓派做的差不多。大部分是国产的。
