### ISSUE TITLE
1.3.0版本Arch Linux证书错误

### ISSUE THREAD

**Issue by gkjgh** [xyuanmu/XX-Mini#127]
我用的是双系统。Windows下，同一个证书，XX-Mini1.3.0运行正常。我改过和XX-Net和XX-Mini的cert_util.py的证书名称，所以XX-Net和XX-Mini用的是同一个证书。Python2.7.13运行XX-Net3.3.2正常。只有Linux下XX-Mini出错。
Python2.7.13错误信息：
```
Jun 17 21:32:56.173 - [ERROR] ssl.wrap_socket(self.connection=<ssl.SSLSocket object at 0x7ff894b0bf50>) failed: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1864) path:github.com:443, errno:1
Jun 17 21:32:56.174 - [ERROR] Except stack:Traceback (most recent call last):
  File "/run/media/user/win/Applications/XX-Mini/lib.egg/proxy_handler.py", line 278, in do_CONNECT_AGENT
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 766, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len)
SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1864)
```
Python降级到2.7.12错误信息：
```
Jun 17 22:02:22.024 - [ERROR] ssl.wrap_socket(self.connection=<ssl.SSLSocket object at 0x7fcaa6d928c0>) failed: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1754) path:github.com:443, errno:1
Jun 17 22:02:22.026 - [ERROR] Except stack:Traceback (most recent call last):
  File "/run/media/user/win/Applications/XX-Mini/lib.egg/proxy_handler.py", line 278, in do_CONNECT_AGENT
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1754)
```

**Comment by jzp820927** [comment]
直接把 win 的证书拿到 linux 下面用呢？

**Comment by gkjgh** [comment]
lib.egg解压为lib文件夹运行正常，打包为zip文件，然后改后缀名为egg，就会报这个错误。请问打包有什么要求吗？

**Comment by jzp820927** [comment]
关于打包，项目首页有说明啊，没遇到过类似情况，只能不明觉厉了。

**Comment by SeaHOH** [comment]
看不懂，就不打包呗。

**Comment by xyuanmu** [comment]
打包没啥要求的，这个错误我也不清楚怎么回事 :sweat_smile:

**Comment by gkjgh** [comment]
这个问题在1.3.2版本神奇的消失了！
