### ISSUE TITLE
release of XX-Mini_linux_darwin_v1.3.2 get a problem

### ISSUE THREAD

**Issue by ywaby** [xyuanmu/XX-Mini#142]
release of XX-Mini_linux_darwin_v1.3.2 get a problem
```
Sep 28 14:07:00.820 - [ERROR] gae_handler.handler TypeError('__init__() takes exactly 4 arguments (5 given)',) https://easylist-downloads.adblockplus.org/easylistchina.txt , retry...
Sep 28 14:07:00.820 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/ywaby/下载/XX-Mini_linux_darwin_v1.3.2/lib.egg/gae_handler.py", line 265, in request_gae_proxy
    response = request_gae_server(request_headers, request_body, url)
  File "/home/ywaby/下载/XX-Mini_linux_darwin_v1.3.2/lib.egg/gae_handler.py", line 135, in request_gae_server
    response = http_dispatch.request(headers, body, url)
  File "/home/ywaby/下载/XX-Mini_linux_darwin_v1.3.2/lib.egg/http_dispatcher.py", line 180, in request
    task = http_common.Task(headers, body, q, url)
TypeError: __init__() takes exactly 4 arguments (5 given)
```

**Comment by gkjgh** [comment]
作者没在Linux上测试过。我用的是Manjaro Linux。同样的错误：

Sep 29 12:54:08.418 - [ERROR] gae_handler.handler TypeError('__init__() takes exactly 4 arguments (5 given)',) https://distrowatch.com/ , retry...
Sep 29 12:54:08.418 - [ERROR] Except stack:Traceback (most recent call last):
  File "/run/media/HD/Applications/XX-Mini/lib.egg/gae_handler.py", line 265, in request_gae_proxy
    response = request_gae_server(request_headers, request_body, url)
  File "/run/media/HD/Applications/XX-Mini/lib.egg/gae_handler.py", line 135, in request_gae_server
    response = http_dispatch.request(headers, body, url)
  File "/run/media/HD/Applications/XX-Mini/lib.egg/http_dispatcher.py", line 180, in request
    task = http_common.Task(headers, body, q, url)
TypeError: __init__() takes exactly 4 arguments (5 given)

但是Windows版没问题。问题可能出在python2上。搭建个Linux环境吧，用虚拟机也不难。

**Comment by ywaby** [comment]
我源代码跑也有同样问题，确实是多了一个参数，不知道什么情况

**Comment by xyuanmu** [comment]
稍等一下，正在修复

**Comment by xyuanmu** [comment]
可以了，重新下载即可。

**Comment by ywaby** [comment]
可以用了，谢了
