### ISSUE TITLE
运行错误，贴出日志

### ISSUE THREAD

**Issue by gbaoye** [xyuanmu/XX-Mini#147]
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "proxy.py", line 26, in <module>
    from config import config
  File "F:\XX-Net\python27.zip\zipextimporter.py", line 82, in load_module
  File "F:\XX-Net\python27.zip\config.py", line 148, in <module>
  File "F:\XX-Net\python27.zip\config.py", line 24, in load
  File "F:\XX-Net\python27.zip\ConfigParser.py", line 305, in read
  File "F:\XX-Net\python27.zip\ConfigParser.py", line 512, in _read
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: F:\XX-Net\proxy.ini, line: 1
'\xef\xbb\xbf[system]\n'

**Comment by xyuanmu** [comment]
你是不是保存过 proxy.ini？保存为 UTF8 不带 signature 的就行了。

**Comment by gbaoye** [comment]
@xyuanmu 好了 用Notepad++编辑
