### ISSUE TITLE
1.3.3在entware上python跑，出现问题，证书问题

### ISSUE THREAD

**Issue by GerGitHub** [xyuanmu/XX-Mini#163]
# 在entware上python跑XXmini 1.3.3，出现问题，证书问题      
               
                                
           Jun 07 04:30:37.127 - [INFO] scan_ip add ip:2607:f8b0:401a:22::b time:1135
           Jun 07 04:30:37.423 - [INFO] scan_ip add ip:2800:3f0:4001:5::9 time:1421
           Jun 07 04:30:37.898 - [INFO] scan_ip add ip:2404:6800:4007:4::c time:855
           Jun 07 04:30:38.420 - [INFO] scan_ip add ip:2607:f8b0:4012:d::15 time:1134
          
           Jun 07 04:07:39.864 - [ERROR] test https://www.microsoft.com e:SSLError('_ssl.c:645: The handshake operation timed out',)
           Jun 07 04:07:39.867 - [ERROR] Except stack:Traceback (most recent call last):
           File "/opt/Shells/XX3/lib.egg/check_local_network.py", line 69, in _test_host response = self.http_client.request("HEAD", url, header, "")
           File "/opt/Shells/XX3/lib.egg/simple_http_client.py", line 528, in request sock = ssl.wrap_socket(sock)
           File "/opt/lib/python2.7/ssl.py", line 943, in wrap_socket
           File "/opt/lib/python2.7/ssl.py", line 611, in __init__
           File "/opt/lib/python2.7/ssl.py", line 840, in do_handshake
           SSLError: ('_ssl.c:645: The handshake operation timed out',)
           
           Jun 07 04:30:41.551 - [INFO] scan_ip add ip:2a00:1450:4017:8::c time:1254
           Jun 07 04:30:42.745 - [INFO] scan_ip add ip:2607:f8b0:4012:d::19 time:1136
           Jun 07 04:30:42.828 - [INFO] scan_ip add ip:2607:f8b0:4012:c::15 time:1122

+ 中间一段是出错问题，证书生成好像有问题；

**Comment by zzd2358** [comment]
https://share.weiyun.com/5KqnYpe   替换cacert.pem删除date目录CA证书重新导入

**Comment by AnyWAT** [comment]
😂(114200)分享资源已经删除
复制3.12.2或更新版XX-Net 内的 code\XXX\gae_proxy\local\cacert.pem 覆盖Mini 的同名文件即可
