### ISSUE TITLE
win10 启动报错

### ISSUE THREAD

**Issue by newcastlecy** [xyuanmu/XX-Mini#17]
Mar 22 22:23:47.317 - [INFO] SSL use version:TLSv1_2
Mar 22 22:23:47.764 - [INFO] load ip range file:...\ip_range.txt
Traceback (most recent call last):
  File "proxy.py", line 262, in <module>
  File "proxy.py", line 220, in main
  File "\python27.zip\cert_util.py", line 537, in init_ca
  File "\python27.zip\cert_util.py", line 496, in import_ca
  File "\python27.zip\cert_util.py", line 306, in import_windows_ca
ImportError: No module named win32elevate

**Comment by xyuanmu** [comment]
抱歉，在xp和win7运行的时候不需要这个模块所以被砍了，你先在xx-mini目录新建一个lib文件夹，下载这份 [win32elevate.py](https://raw.githubusercontent.com/XX-net/XX-Net/master/python27/1.0/lib/win32/win32elevate.py) 先放进去（用下载工具下载，别用浏览器打开）。
