### ISSUE TITLE
我尝试在梅林固件上运行，遇到这个错误，怎么解决呢？

### ISSUE THREAD

**Issue by zhyoi** [xyuanmu/XX-Mini#29]
Traceback (most recent call last):
  File "proxy.py", line 262, in <module>
    main()
  File "proxy.py", line 214, in main
    google_ip.check()
  File "/jffs/XX-Mini/lib.egg/lib/google_ip.py", line 42, in check
    self.reset()
  File "/jffs/XX-Mini/lib.egg/lib/google_ip.py", line 85, in reset
    self.search_more_google_ip()
  File "/jffs/XX-Mini/lib.egg/lib/google_ip.py", line 588, in search_more_google_ip
    p.start()
  File "/opt/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

**Comment by xyuanmu** [comment]
开不了足够的线程，你打开 proxy.ini 修改 max_scan_ip_thread_num = 50，50改成20看看能否启动。

**Comment by zhyoi** [comment]
已经改成5了，还是开不起来。
运行XX-Net就不会出现这个问题，一样的配置。
另外我发现监听端口改成0.0.0.0以后，不会用路由器的地址192.168.1.1，而是用的WAN的公网IP地址。

**Comment by xyuanmu** [comment]
你下载1.0版本试试：https://github.com/xyuanmu/XX-Mini/releases/download/1.0/XX-Mini_linux_v1.0.zip

**Comment by zhyoi** [comment]
Traceback (most recent call last):
  File "proxy.py", line 77, in <module>
    import proxy_handler
  File "/jffs/XX-Mini/lib.egg/lib/proxy_handler.py", line 20, in <module>
  File "/jffs/XX-Mini/lib.egg/lib/gae_handler.py", line 23, in <module>
  File "/jffs/XX-Mini/lib.egg/lib/connect_manager.py", line 43, in <module>
  File "/jffs/XX-Mini/lib.egg/lib/google_ip.py", line 644, in <module>
  File "/jffs/XX-Mini/lib.egg/lib/google_ip.py", line 42, in __init__
  File "/jffs/XX-Mini/lib.egg/lib/google_ip.py", line 84, in reset
  File "/jffs/XX-Mini/lib.egg/lib/google_ip.py", line 579, in search_more_google_ip
  File "/opt/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/jffs/XX-Mini/lib.egg/lib/google_ip.py", line 558, in scan_ip_worker
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/jffs/XX-Mini/lib.egg/lib/google_ip.py", line 558, in scan_ip_worker
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/jffs/XX-Mini/lib.egg/lib/google_ip.py", line 558, in scan_ip_worker
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/jffs/XX-Mini/lib.egg/lib/google_ip.py", line 558, in scan_ip_worker
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/jffs/XX-Mini/lib.egg/lib/google_ip.py", line 558, in scan_ip_worker
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/jffs/XX-Mini/lib.egg/lib/google_ip.py", line 558, in scan_ip_worker
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/jffs/XX-Mini/lib.egg/lib/google_ip.py", line 558, in scan_ip_worker
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/jffs/XX-Mini/lib.egg/lib/google_ip.py", line 558, in scan_ip_worker
AttributeError: 'NoneType' object has no attribute 'exception'
不行，直接退出了

**Comment by xyuanmu** [comment]
看来精简版不适用所有Linux系统，我手头也没有工具可以测试，你先用回XX-Net吧。

**Comment by zhyoi** [comment]
嗯，已经用回XX-Net了，等完善了再来试一下。

**Comment by jzp820927** [comment]
路由固件这么小，应该很多依赖环境都不完整，够得折腾的

**Comment by xyuanmu** [comment]
刚才查看了xx-net启动的代码，有一个重建threading栈大小的代码，你试试在 proxy.py 第40行左右加上这两行代码，看能否启动：
```py
import threading
threading.stack_size(128*1024)

**Comment by zhyoi** [comment]
出现以下错误
File "/jffs/XX-Mini/proxy.py", line 190
    error = u'某些安全软件(夿%s)可能和本软件存在冲突，造成 CPU 占用过高。\n如有此现象建议暂时退出此安全软件来继续运行XX-Mini' % ','.join(softwares)
SyntaxError: (unicode error) 'utf8' codec can't decode bytes in position 0-1: unexpected end of data

**Comment by jzp820927** [comment]
语法错误，好像和编码有关系

**Comment by xyuanmu** [comment]
保存的时候是utf-8格式吗？
或者在另一个平台改好文件并保存为utf-8格式，再替换过去。

**Comment by zhyoi** [comment]
非常感谢，可以正常运行了。

**Comment by xyuanmu** [comment]
不客气，解决了就好
