### ISSUE TITLE
小白咨询问题

### ISSUE THREAD

**Issue by simi11king** [xyuanmu/XX-Mini#32]
对代码和信息完全不了解，用的XX-NET，部署了appid，如下问题：
系统为arch，安装了python2.7和3，最近又搞了一台chromebook（python2.7），希望能在chromebook里使用
为降低兼容性问题，选择这个，但是无论是arch还是chromebook均提示：
在arch里用的python2.7 ./proxy.py

Traceback (most recent call last):
  File "proxy.py", line 53, in <module>
    from OpenSSL import version as openssl_version
  File "/home/tux/tools/xx/lib.egg/lib/OpenSSL/__init__.py", line 36, in <module>
ImportError: cannot import name crypto

上述问题是什么意思？openssl版本不一致？xx-net用的是3,正常运行中。

**Comment by xyuanmu** [comment]
试试如下方法：
* 在 XX-Mini 目录新建一个lib文件夹
* 将python27版本的 XX-Net\python27\1.0\lib 下的 crypto 文件夹复制到上述lib文件夹中

**Comment by xyuanmu** [comment]
知道问题所在了，你应该是用的32位系统吧，手动安装 pyOpenSSL，自带的是64位的，考虑下个 Linux 版本开始删掉OpenSSL以免出错。

**Comment by simi11king** [comment]
哦，我的系统确实是64位系统的，手动安装pyOpenSSL，似乎部分arch的库未更新python2的文件，更新失败了，我再查查吧。。。。

**Comment by jzp820927** [comment]
pip install pyopenssl

**Comment by yeahwu** [comment]
python-OpenSSL
libffi-dev
python-gtk2
python-appindicator
libnss3-tools
该打的补丁都打上
