### ISSUE TITLE
可喜可贺，XXMINI 终于出 Releases 了！狂点 1万个赞 ！

### ISSUE THREAD

**Issue by jzp820927** [xyuanmu/XX-Mini#40]
python 3 版本的 xxmini 终于 Releases 了，看来下压缩包的文件，和 配置文件，打包和认证也做好了，@xyuanmu 的做事效率果然高，以后我就是 xxmini 的忠实粉丝了，XXNET 切换到备胎模式了。

**Comment by fletchere** [comment]
恭喜恭喜，不过，还有有待完善，无论是运行 python proxy还是python goagent-gtk.py都起不来。

**Comment by xyuanmu** [comment]
@fletchere `python3 proxy.py`，`python goagent-gtk.py`，goagent-gtk.py是python2写的。

**Comment by yeahwu** [comment]
报错如下
```
Traceback (most recent call last):
  File "proxy.py", line 63, in <module>
    from OpenSSL import version as openssl_version
  File "/usr/local/lib/python3.4/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python3.4/dist-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python3.4/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
ImportError: No module named 'cryptography'
```
python2正常 ，OpenSSL也已安装

**Comment by jzp820927** [comment]
@fletchere python 是默认链接到 py2 的，要用 python3 执行
@yeahwu 我都从来没出过错，不晓得为啥你老是出错

**Comment by yeahwu** [comment]
是的，py3就是搞不转哪

**Comment by xyuanmu** [comment]
@yeahwu 你python3没有安装 cryptography，OpenSSL需要这个库的支持。

**Comment by jzp820927** [comment]
我都是 apt-get install pyopenssl ，这一个，就可以运行了。ubuntu 应该是可以自动解决依赖问题的，所以如果 OpenSSL需要 cryptography 库支持，在安装 pyopenssl 的时候，应该可以一并安装。

**Comment by fletchere** [comment]
@xyuanmu 我的是arch，默认的python是python 3，错误如下：
[user@host:XX-Mini-P3_linux_darwin_v1.0]$ python3 goagent-gtk.py 
  File "goagent-gtk.py", line 104
    os.chmod(filename, 0755)
                          ^
SyntaxError: invalid token

[user@host:XX-Mini-P3_linux_darwin_v1.0]$ python3 proxy.py 
Traceback (most recent call last):
  File "proxy.py", line 62, in <module>
    from local.config import config
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/zhou0/Downloads/XX-Mini-P3_linux_darwin_v1.0/pythonlib.egg/local/config.py", line 137, in <module>
  File "/home/zhou0/Downloads/XX-Mini-P3_linux_darwin_v1.0/pythonlib.egg/local/config.py", line 45, in load
  File "/usr/lib/python3.5/configparser.py", line 797, in get
    d)
  File "/usr/lib/python3.5/configparser.py", line 393, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.5/configparser.py", line 443, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%e}r_WY^k'

**Comment by jzp820927** [comment]
不用 python3 goagent-gtk.py  ，试试 python3 proxy.py ？

**Comment by xyuanmu** [comment]
@fletchere  `python3 proxy.py`，`python goagent-gtk.py`，goagent-gtk.py是python2写的。

**Comment by fletchere** [comment]
@jzp820927 上面的报错都两个都试过了。

**Comment by yeahwu** [comment]
还是报错，那个'cryptography'就是安装不上去呀，蛋疼

**Comment by jzp820927** [comment]
你怎么安装的啊，安装的时候提示什么啊？
