### ISSUE TITLE
ImportError: No module named '_socket'

### ISSUE THREAD

**Issue by jdfq** [xyuanmu/XX-Mini#65]
Traceback (most recent call last):
  File "proxy.py", line 62, in <module>
    from local.config import config
  File "E:\程序\代理\XX-Mini-P3_win_v1.2\python35.zip\local\config.py", line 8,
in <module>
  File "socket.py", line 49, in <module>
ImportError: No module named '_socket'

win7家庭普通版

**Comment by jdfq** [comment]
好像解决了，因为压缩包中缺少pythonlib文件夹

**Comment by jdfq** [comment]
[INFO] GAE CONNECT redirector.googlevideo.com:443
[WARNING] Method CONNECT not support in GAEProxy for redir
ector.googlevideo.com:443

**Comment by xyuanmu** [comment]
确实，已经重新上传了压缩包。
