### ISSUE TITLE
1.2.7 linux其动不了，日志如下。

### ISSUE THREAD

**Issue by fletchere** [xyuanmu/XX-Mini#68]
--------------------------------------------------------------------------------
May 12 12:47:00.442 - [INFO] SSL use version:TLSv1_2
May 12 12:47:00.443 - [INFO] OpenSSL support alpn
May 12 12:47:00.453 - [INFO] load ip range file:/home/zhou0/XX-Mini/ip_range.txt
Traceback (most recent call last):
  File "proxy.py", line 104, in <module>
    import proxy_handler
  File "/home/zhou0/XX-Mini/lib.egg/lib/proxy_handler.py", line 20, in <module>
  File "/home/zhou0/XX-Mini/lib.egg/lib/gae_handler.py", line 26, in <module>
  File "/home/zhou0/XX-Mini/lib.egg/lib/google_ip.py", line 723, in <module>
  File "/home/zhou0/XX-Mini/lib.egg/lib/google_ip.py", line 52, in __init__
  File "/home/zhou0/XX-Mini/lib.egg/lib/google_ip.py", line 93, in reset
  File "/home/zhou0/XX-Mini/lib.egg/lib/google_ip.py", line 125, in load_ip
AttributeError: IpManager instance has no attribute 'default_good_ip_file'

**Comment by wzdnzd** [comment]
把之前的data文件夹拷过去 我的windows下一开始也这样 拷过去就好了  以前是解压过去覆盖 但是之前是python3版的  所以这次我把数据拷过来了 @fletchere

**Comment by xyuanmu** [comment]
抱歉，一个小错误。已更新了文件，重新下载即可。
