### ISSUE TITLE
Python 2.6.6 版本 系统centos vps上运行xx mini出错，求助

### ISSUE THREAD

**Issue by boyyao** [xyuanmu/XX-Mini#73]
[root@centos XX-Mini]# python proxy.py
--------------------------------------------------------------------------------
XX-Mini Version     : 1.2.7 (python/2.6.6 pyopenssl/0.13.1)
Listen Address      : 127.0.0.1:8087
Setting File        : proxy.ini
GAE APPID           : Using Public APPID
Pac Server          : http://127.0.0.1:8086/proxy.pac
CA File             : http://127.0.0.1:8086/CA.crt
Pac File            : file:///mnt/diskd/XX-Mini/data/proxy.pac
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "proxy.py", line 104, in <module>
    import proxy_handler
  File "/mnt/diskd/XX-Mini/lib/proxy_handler.py", line 20, in <module>
    import gae_handler
  File "/mnt/diskd/XX-Mini/lib/gae_handler.py", line 22, in <module>
    from appids_manager import appid_manager
  File "/mnt/diskd/XX-Mini/lib/appids_manager.py", line 11, in <module>
    import check_ip
  File "/mnt/diskd/XX-Mini/lib/check_ip.py", line 16, in <module>
    import socks
  File "/mnt/diskd/XX-Mini/lib/socks.py", line 207
    if type not in {socket.SOCK_STREAM, socket.SOCK_DGRAM}:
                                      ^
SyntaxError: invalid syntax

试过xxnet也是同样错误。不知道是不是我的python版本不对还是缺少库？如何解决？谢谢。

**Comment by yeahwu** [comment]
照上面的内容改一下，试试
https://github.com/XX-net/XX-Net/commit/26f9a75b0f2dab26991c0d40893c3be99f690e8b

**Comment by jzp820927** [comment]
最基本的语法错误，你的 python 版本太低了。
