### ISSUE TITLE
@xyuanmu 兄，看看这个报错是啥意思？

### ISSUE THREAD

**Issue by jzp820927** [xyuanmu/XX-Mini#75]
May 26 05:38:44.122 - [ERROR] google_ip.runJob fail:TypeError("unsupported operand type(s) for +=: 'int' and 'NoneType'",)
May 26 05:38:44.122 - [ERROR] Except stack:Traceback (most recent call last):
  File "/fq_service/3_proxy/1_gae/xx-mini/lib.egg/lib/google_ip.py", line 619, in scan_ip_worker
    result = check_ip.test_gae_ip2(ip)
  File "/fq_service/3_proxy/1_gae/xx-mini/lib.egg/lib/check_ip.py", line 213, in test_gae_ip2
    conn = hyper.HTTP20Connection(ssl_sock, host='%s.appspot.com'%appid, ip=ip, port=443)
  File "/fq_service/3_proxy/1_gae/xx-mini/lib.egg/lib/hyper/http20/connection.py", line 114, in __init__
    self._send_preamble()
  File "/fq_service/3_proxy/1_gae/xx-mini/lib.egg/lib/hyper/http20/connection.py", line 282, in _send_preamble
    self._sock.send(b'PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n')
  File "/fq_service/3_proxy/1_gae/xx-mini/lib.egg/lib/hyper/common/bufsocket.py", line 110, in send
    self.flush()
  File "/fq_service/3_proxy/1_gae/xx-mini/lib.egg/lib/hyper/common/bufsocket.py", line 123, in flush
    start += sended
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

好像是在统计 IP 这儿报错了，不过前面有正常显示过统计IP信息，具体是下面这条日志：
May 26 03:19:17.057 - [INFO] good ip num:69, bad ip num:2

任何在这个 IP 统计日志的后面就一直报上面的错误了。

**Comment by yangchangyz** [comment]
@我有时也类似

**Comment by xyuanmu** [comment]
不是统计IP出错，是发送数据时出错，丢失了一个数值，重启可以解决，现在身边没有电脑，过段时间再看看吧。

**Comment by jzp820927** [comment]
我还以为你 金盆洗手了。
