### ISSUE TITLE
python3 linux git 版根本没法运行，大家是怎么运行的。

### ISSUE THREAD

**Issue by torappinfo** [xyuanmu/XX-Mini#83]
$ python3 proxy.py
Traceback (most recent call last):
  File "proxy.py", line 62, in <module>
    from config import config
  File "～/git/XX-Mini/lib/config.py", line 5, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser'

修改掉ConfigParser的话也还有很多问题，看大家推荐说linux版python3是没问题的，但我从来就没成功过。

**Comment by xyuanmu** [comment]
你下载的是Python2版
https://github.com/xyuanmu/XX-Mini/tree/python3
