### ISSUE TITLE
安装python-pyopenssl时，出现错误

### ISSUE THREAD

**Issue by luckyfatpig** [xyuanmu/XX-Mini#99]
错误提示：error：dependency python-crytography of package python-pyopenssl cannot be found,try updating your package lists

我猜是缺少了依赖包，在哪能找到？或者能不能给出软件源地址，我装的那个python-pyopenssl也是自己找的

**Comment by jzp820927** [comment]
是按照 wiki 的教程，一步一步操作的吗？

**Comment by CNMan** [comment]
debian 或 ubuntu
```
apt-get install python-crytography python-pyopenssl
```

RHEL 或 Fedora

```
yum install python-crytography python-pyopenssl
```

**Comment by luckyfatpig** [comment]
我要安装在openwrt里

CNMan <notifications@github.com> 於 2016年9月2日 週五 21:44 寫道：

**Comment by CNMan** [comment]
```
opkg install python-crytography python-pyopenssl
```

**Comment by luckyfatpig** [comment]
要安裝的两个软件源都没有，能提供软件源或软件包吗？

**Comment by luckyfatpig** [comment]
依赖包和python-openssl都找到了也安装成功，现在还缺个pyopenssl

**Comment by luckyfatpig** [comment]
安装完pyopenssl运行又出现这个错误：

root@Gargoyle:~# python /etc/XX-Mini/proxy.py
Traceback (most recent call last):
  File "/etc/XX-Mini/proxy.py", line 63, in <module>
    from OpenSSL import version as openssl_version
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: File not found

**Comment by luckyfatpig** [comment]
用xx-net也是这个问题……

**Comment by jzp820927** [comment]
https://github.com/xyuanmu/XX-Mini/wiki/OpenWrt-%E4%B8%8B%E9%85%8D%E7%BD%AE-XX-Mini
参考下这个 wiki 和里面的2个 issues，那2个 issues 是别人成功运行的经验，值得一看

**Comment by luckyfatpig** [comment]
原因知道，是新版openssl的依赖包太多，只能用回旧版的openssl

**Comment by jzp820927** [comment]
能用就行了，其实只要 IP 直连好，http/2 影响不大。http/2 只是对高延时的 IP，有优化作用。而且也不是太明显。

**Comment by luckyfatpig** [comment]
另外想问一下，有些网站pac没有，怎么能添加进去或者用软件解決？

天朝屁民 <notifications@github.com> 於 2016年9月4日 週日 23:39 寫道：

**Comment by jzp820927** [comment]
2个方法，1是提交网址到 gfwlist 项目的 issues，2是自己编辑 pac 文件添加网址。

**Comment by roc1010kmt** [comment]
@luckyfatpig 我安裝python-pyopenssl_16.0.0-1_ar71xx.ipk版,啟動xxnet和你的錯誤提示一樣.
是安裝舊版就可以嗎?在哪裡可以找到?能發我一個嗎?

**Comment by roc1010kmt** [comment]
@luckyfatpig # python /tmp/xx/proxy.py
Traceback (most recent call last):
  File "/tmp/xx/proxy.py", line 63, in <module>
    from OpenSSL import version as openssl_version
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: File not found

**Comment by luckyfatpig** [comment]
http://pan.baidu.com/share/link?shareid=3469990355&uk=2486271132

强制安装就行

roc1010kmt <notifications@github.com> 於 2016年9月7日 週三 03:04 寫道：

**Comment by roc1010kmt** [comment]
@luckyfatpig pyopenssl_16啟動不了出錯,pyopenssl_10可以啟動.
不知為什麼路由器比電腦慢好多?youtube720p非常卡基本看不了.
電腦上就非常順暢.為什麼?

**Comment by luckyfatpig** [comment]
要看扫到的ip是否快（刚开始扫ip比较少，等ip多了会有好转），另外路由器的处理器比电脑的慢多了，连接时处理多个ip是有点转不过来，目前使用感觉就是有时1080p都没问题，有时慢得好像打不开一样

roc1010kmt <notifications@github.com> 於 2016年9月7日 週三 08:20 寫道：

**Comment by roc1010kmt** [comment]
@luckyfatpig ip是電腦掃的,直接拷過去的.應該一樣.就是速度慢好多.
有時還會自動退出?xxnet你是放在usb還是路由器內存?

**Comment by luckyfatpig** [comment]
我用的wndr4300直接放路由上的

roc1010kmt <notifications@github.com> 於 2016年9月7日 週三 08:50 寫道：

**Comment by jzp820927** [comment]
@roc1010kmt 建议更换树莓派，那硬件比电脑还流弊。
